import type {
  ArchitectureDecision,
  ChangeSet,
  HistoryEvent,
  MemoryDocument,
  Project,
  ProjectGraph,
  Repository,
  Requirement,
  SecurityFinding,
} from "./types";

/**
 * Demo seed data. Everything here is explicitly labelled DEMO so the UI can
 * distinguish it from data produced by real integrations.
 */

export const DEMO_PROJECT_ID = "prj_genesis_demo";

const now = new Date("2026-08-24T10:30:00Z");
const iso = (minutesAgo: number) => new Date(now.getTime() - minutesAgo * 60_000).toISOString();

export const demoProject: Project = {
  id: DEMO_PROJECT_ID,
  name: "Genesis AI Demo",
  description:
    "Reference project used to demonstrate HPIM retrieval, agent orchestration and change-impact analysis.",
  stack: ["React", "TypeScript", "Node.js", "Express", "MongoDB"],
  health: "warning",
  createdAt: iso(60 * 24 * 40),
  origin: "DEMO",
};

export const demoRequirements: Requirement[] = [
  {
    id: "REQ-001",
    projectId: DEMO_PROJECT_ID,
    title: "User authentication",
    description:
      "Users must authenticate with email and password and receive a signed JWT access token valid for 15 minutes.",
    type: "functional",
    priority: "critical",
    status: "implemented",
    source: "Stakeholder interview",
    linkedComponents: ["AuthService", "AuthController", "LoginAPI"],
    linkedFiles: ["src/services/auth.ts", "src/controllers/authController.ts"],
    createdAt: iso(60 * 24 * 30),
    updatedAt: iso(60 * 24 * 3),
    origin: "DEMO",
  },
  {
    id: "REQ-002",
    projectId: DEMO_PROJECT_ID,
    title: "Secure login and session handling",
    description:
      "Login attempts must be rate limited, credentials hashed with bcrypt, and sessions invalidated on logout.",
    type: "non-functional",
    priority: "high",
    status: "approved",
    source: "Security review",
    linkedComponents: ["AuthService", "SessionMiddleware"],
    linkedFiles: ["src/middleware/session.ts"],
    createdAt: iso(60 * 24 * 28),
    updatedAt: iso(60 * 24 * 5),
    origin: "DEMO",
  },
  {
    id: "REQ-003",
    projectId: DEMO_PROJECT_ID,
    title: "Project management",
    description: "Users can create, list and archive projects; each project scopes all other entities.",
    type: "functional",
    priority: "high",
    status: "implemented",
    source: "Product backlog",
    linkedComponents: ["ProjectService", "ProjectAPI"],
    linkedFiles: ["src/services/project.ts"],
    createdAt: iso(60 * 24 * 26),
    updatedAt: iso(60 * 24 * 6),
    origin: "DEMO",
  },
  {
    id: "REQ-004",
    projectId: DEMO_PROJECT_ID,
    title: "AI-assisted code modification",
    description:
      "The platform proposes code modifications only after a change-impact analysis and explicit user approval.",
    type: "functional",
    priority: "critical",
    status: "approved",
    source: "Product vision",
    linkedComponents: ["AgentOrchestrator", "HPIM"],
    linkedFiles: ["src/services/orchestrator.ts"],
    createdAt: iso(60 * 24 * 20),
    updatedAt: iso(60 * 24 * 2),
    origin: "DEMO",
  },
  {
    id: "REQ-005",
    projectId: DEMO_PROJECT_ID,
    title: "Audit trail of all agent actions",
    description: "Every agent execution is recorded with actor, timestamp, inputs used and structured output.",
    type: "non-functional",
    priority: "medium",
    status: "draft",
    source: "Compliance",
    linkedComponents: ["ProjectHistory"],
    linkedFiles: [],
    createdAt: iso(60 * 24 * 12),
    updatedAt: iso(60 * 24 * 12),
    origin: "DEMO",
  },
];

export const demoDecisions: ArchitectureDecision[] = [
  {
    id: "ADR-001",
    projectId: DEMO_PROJECT_ID,
    title: "Use JWT for authentication",
    decision: "Stateless JWT access tokens signed with RS256, 15 minute expiry.",
    reason: "Horizontal scalability without shared session storage.",
    alternatives: ["Server-side sessions in Redis", "Opaque tokens with introspection"],
    consequences: ["Token revocation needs an explicit deny-list", "Short expiry requires a refresh mechanism"],
    author: "architecture@genesis",
    createdAt: iso(60 * 24 * 29),
    origin: "DEMO",
  },
  {
    id: "ADR-002",
    projectId: DEMO_PROJECT_ID,
    title: "MongoDB as primary datastore",
    decision: "Document model for projects, requirements, history and agent runs.",
    reason: "Flexible schemas for evolving agent payloads and project history.",
    alternatives: ["PostgreSQL with JSONB"],
    consequences: ["Application-level referential integrity", "Indexes required on projectId"],
    author: "architecture@genesis",
    createdAt: iso(60 * 24 * 27),
    origin: "DEMO",
  },
  {
    id: "ADR-003",
    projectId: DEMO_PROJECT_ID,
    title: "React + TypeScript frontend",
    decision: "Single-page dashboard with strict TypeScript and a shared design system.",
    reason: "Dense developer tooling UI with strong typing across API contracts.",
    alternatives: ["Server-rendered templates"],
    consequences: ["Client bundle budget must be monitored"],
    author: "frontend@genesis",
    createdAt: iso(60 * 24 * 25),
    origin: "DEMO",
  },
  {
    id: "ADR-004",
    projectId: DEMO_PROJECT_ID,
    title: "Hybrid memory (vector + graph + history)",
    decision: "HPIM fuses semantic search, a dependency graph and an append-only history log.",
    reason: "Isolated prompts cannot reason about cross-component impact.",
    alternatives: ["Vector store only", "Full-context prompting"],
    consequences: ["Three stores must stay consistent on every write"],
    author: "architecture@genesis",
    createdAt: iso(60 * 24 * 18),
    origin: "DEMO",
  },
];

export const demoGraph: ProjectGraph = {
  lastUpdated: iso(60 * 18),
  origin: "DEMO",
  nodes: [
    { id: "LoginAPI", label: "LoginAPI", kind: "api", file: "src/routes/auth.routes.ts", summary: "POST /api/auth/login" },
    {
      id: "AuthController",
      label: "AuthController",
      kind: "controller",
      file: "src/controllers/authController.ts",
      methods: ["login()", "logout()", "me()"],
      language: "TypeScript",
    },
    {
      id: "AuthService",
      label: "AuthService",
      kind: "service",
      file: "src/services/auth.ts",
      methods: ["login()", "refreshToken()", "logout()", "verify()"],
      language: "TypeScript",
      summary: "Issues and verifies access tokens.",
    },
    {
      id: "UserRepository",
      label: "UserRepository",
      kind: "repository",
      file: "src/repositories/userRepository.ts",
      methods: ["findByEmail()", "create()", "update()"],
      language: "TypeScript",
    },
    { id: "UserModel", label: "User", kind: "model", file: "src/models/user.ts", language: "TypeScript" },
    { id: "MongoDB", label: "MongoDB", kind: "database", summary: "Primary datastore" },
    {
      id: "SessionMiddleware",
      label: "SessionMiddleware",
      kind: "middleware",
      file: "src/middleware/session.ts",
      language: "TypeScript",
    },
    { id: "ProjectAPI", label: "ProjectAPI", kind: "api", file: "src/routes/project.routes.ts" },
    {
      id: "ProjectService",
      label: "ProjectService",
      kind: "service",
      file: "src/services/project.ts",
      methods: ["create()", "list()", "archive()"],
    },
    { id: "APIGateway", label: "API Gateway", kind: "component", file: "src/server.ts" },
    { id: "Frontend", label: "Frontend", kind: "component", file: "frontend/src/main.tsx" },
    { id: "AuthTest", label: "auth.test.ts", kind: "test", file: "tests/auth.test.ts" },
    { id: "LoginTest", label: "login.test.ts", kind: "test", file: "tests/login.test.ts" },
  ],
  edges: [
    { from: "Frontend", to: "APIGateway", kind: "CALLS" },
    { from: "APIGateway", to: "LoginAPI", kind: "EXPOSES" },
    { from: "APIGateway", to: "ProjectAPI", kind: "EXPOSES" },
    { from: "LoginAPI", to: "AuthController", kind: "CALLS" },
    { from: "AuthController", to: "AuthService", kind: "CALLS" },
    { from: "AuthService", to: "UserRepository", kind: "USES" },
    { from: "UserRepository", to: "UserModel", kind: "USES" },
    { from: "UserRepository", to: "MongoDB", kind: "DEPENDS_ON" },
    { from: "SessionMiddleware", to: "AuthService", kind: "DEPENDS_ON" },
    { from: "LoginAPI", to: "SessionMiddleware", kind: "REQUIRES" },
    { from: "ProjectAPI", to: "ProjectService", kind: "CALLS" },
    { from: "ProjectService", to: "MongoDB", kind: "DEPENDS_ON" },
    { from: "AuthTest", to: "AuthService", kind: "USES" },
    { from: "LoginTest", to: "LoginAPI", kind: "USES" },
    { from: "AuthService", to: "UserModel", kind: "IMPORTS" },
  ],
};

export const demoRepository: Repository = {
  connected: true,
  provider: "github",
  fullName: "genesis-ai/demo-platform",
  branch: "main",
  lastIndexedAt: iso(60 * 18),
  origin: "DEMO",
  frameworks: ["Express", "React", "Vitest"],
  packages: [
    { name: "express", version: "4.19.2" },
    { name: "jsonwebtoken", version: "9.0.2", risk: "medium" },
    { name: "mongoose", version: "8.4.0" },
    { name: "bcryptjs", version: "2.4.3" },
    { name: "react", version: "19.0.0" },
    { name: "lodash", version: "4.17.20", risk: "high" },
  ],
  files: [
    {
      path: "src/services/auth.ts",
      language: "TypeScript",
      loc: 184,
      exports: ["AuthService"],
      imports: ["jsonwebtoken", "./userRepository", "../models/user"],
      symbols: ["AuthService", "login", "refreshToken", "logout", "verify"],
    },
    {
      path: "src/controllers/authController.ts",
      language: "TypeScript",
      loc: 96,
      exports: ["AuthController"],
      imports: ["../services/auth"],
      symbols: ["AuthController", "login", "logout", "me"],
    },
    {
      path: "src/repositories/userRepository.ts",
      language: "TypeScript",
      loc: 71,
      exports: ["UserRepository"],
      imports: ["../models/user"],
      symbols: ["UserRepository", "findByEmail", "create", "update"],
    },
    {
      path: "src/models/user.ts",
      language: "TypeScript",
      loc: 48,
      exports: ["User", "UserSchema"],
      imports: ["mongoose"],
      symbols: ["User", "UserSchema"],
    },
    {
      path: "src/middleware/session.ts",
      language: "TypeScript",
      loc: 54,
      exports: ["sessionMiddleware"],
      imports: ["../services/auth"],
      symbols: ["sessionMiddleware"],
    },
    {
      path: "src/routes/auth.routes.ts",
      language: "TypeScript",
      loc: 32,
      exports: ["authRouter"],
      imports: ["express", "../controllers/authController"],
      symbols: ["authRouter"],
    },
    {
      path: "src/services/project.ts",
      language: "TypeScript",
      loc: 120,
      exports: ["ProjectService"],
      imports: ["../models/project"],
      symbols: ["ProjectService", "create", "list", "archive"],
    },
    {
      path: "tests/auth.test.ts",
      language: "TypeScript",
      loc: 140,
      exports: [],
      imports: ["../src/services/auth"],
      symbols: ["describe", "it"],
      isTest: true,
    },
    {
      path: "tests/login.test.ts",
      language: "TypeScript",
      loc: 88,
      exports: [],
      imports: ["../src/routes/auth.routes"],
      symbols: ["describe", "it"],
      isTest: true,
    },
  ],
};

export const demoHistory: HistoryEvent[] = [
  {
    id: "evt-1",
    projectId: DEMO_PROJECT_ID,
    actor: "Coding Agent",
    type: "agent",
    description: "Proposed AuthService changes for token rotation",
    components: ["AuthService"],
    files: ["src/services/auth.ts"],
    timestamp: iso(0),
    origin: "DEMO",
  },
  {
    id: "evt-2",
    projectId: DEMO_PROJECT_ID,
    actor: "Architecture Agent",
    type: "agent",
    description: "Completed change-impact analysis for authentication subsystem",
    components: ["AuthService", "AuthController", "LoginAPI"],
    files: [],
    timestamp: iso(5),
    origin: "DEMO",
  },
  {
    id: "evt-3",
    projectId: DEMO_PROJECT_ID,
    actor: "alex@genesis",
    type: "requirement",
    description: "Requirement REQ-002 updated with rate limiting acceptance criteria",
    components: ["AuthService"],
    files: [],
    timestamp: iso(10),
    origin: "DEMO",
  },
  {
    id: "evt-4",
    projectId: DEMO_PROJECT_ID,
    actor: "HPIM",
    type: "memory",
    description: "Project dependency graph rebuilt (13 nodes, 15 relationships)",
    components: [],
    files: [],
    timestamp: iso(60 * 18),
    origin: "DEMO",
  },
  {
    id: "evt-5",
    projectId: DEMO_PROJECT_ID,
    actor: "Repository Scanner",
    type: "repository",
    description: "Indexed genesis-ai/demo-platform@main — 9 files, 3 frameworks",
    components: [],
    files: [],
    timestamp: iso(60 * 18 + 4),
    origin: "DEMO",
  },
  {
    id: "evt-6",
    projectId: DEMO_PROJECT_ID,
    actor: "architecture@genesis",
    type: "decision",
    description: "ADR-004 recorded: hybrid memory (vector + graph + history)",
    components: ["HPIM"],
    files: [],
    timestamp: iso(60 * 24 * 18),
    origin: "DEMO",
  },
];

export const demoMemoryDocs: MemoryDocument[] = [
  ...demoRequirements.map((r) => ({
    id: `mem-${r.id}`,
    projectId: DEMO_PROJECT_ID,
    kind: "requirement" as const,
    title: r.title,
    content: `${r.title}. ${r.description}`,
    ...(r.linkedComponents[0] ? { component: r.linkedComponents[0] } : {}),
    ...(r.linkedFiles[0] ? { file: r.linkedFiles[0] } : {}),
    updatedAt: r.updatedAt,
  })),
  ...demoDecisions.map((d) => ({
    id: `mem-${d.id}`,
    projectId: DEMO_PROJECT_ID,
    kind: "decision" as const,
    title: d.title,
    content: `${d.title}. ${d.decision} Reason: ${d.reason}`,
    updatedAt: d.createdAt,
  })),
  {
    id: "mem-doc-auth",
    projectId: DEMO_PROJECT_ID,
    kind: "code",
    title: "AuthService overview",
    content:
      "AuthService issues JWT access tokens, verifies signatures and clears sessions on logout. It depends on UserRepository for credential lookup and has no refresh token support yet.",
    component: "AuthService",
    file: "src/services/auth.ts",
    updatedAt: iso(60 * 18),
  },
  {
    id: "mem-doc-api",
    projectId: DEMO_PROJECT_ID,
    kind: "api",
    title: "Authentication API",
    content:
      "POST /api/auth/login returns an access token. POST /api/auth/logout clears the session. There is currently no POST /api/auth/refresh endpoint.",
    component: "LoginAPI",
    file: "src/routes/auth.routes.ts",
    updatedAt: iso(60 * 18),
  },
  {
    id: "mem-doc-jwt",
    projectId: DEMO_PROJECT_ID,
    kind: "doc",
    title: "JWT handling documentation",
    content:
      "Tokens are signed with RS256 and expire after 15 minutes. Revocation relies on a deny-list keyed by token id (jti).",
    component: "AuthService",
    file: "docs/auth.md",
    updatedAt: iso(60 * 24 * 4),
  },
];

export const demoSecurityFindings: SecurityFinding[] = [
  {
    id: "SEC-001",
    title: "Refresh tokens would be stored without rotation",
    location: "src/services/auth.ts",
    severity: "high",
    risk: "A leaked long-lived refresh token grants indefinite access.",
    recommendation: "Rotate refresh tokens on every use and persist a hashed token family id.",
    origin: "DEMO",
  },
  {
    id: "SEC-002",
    title: "Outdated dependency: lodash 4.17.20",
    location: "package.json",
    severity: "medium",
    risk: "Known prototype pollution advisories in versions below 4.17.21.",
    recommendation: "Upgrade lodash to 4.17.21 or replace with native utilities.",
    origin: "DEMO",
  },
  {
    id: "SEC-003",
    title: "Login endpoint lacks rate limiting",
    location: "src/routes/auth.routes.ts",
    severity: "medium",
    risk: "Credential stuffing and brute force attempts are unbounded.",
    recommendation: "Add per-IP and per-account rate limiting middleware.",
    origin: "DEMO",
  },
];

export const demoChanges: ChangeSet[] = [];
